spring:
  datasource:
    url: jdbc:postgresql://0.0.0.0:5432/test
    username: usr
    password: pass
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: '600000'
      idle-timeout: '3000000'
      maximum-pool-size: '5'
      max-lifetime: '3000000'
      auto-commit: 'true'
      minimum-idle: '2'
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
        use_sql_comments: 'true'
        format_sql: 'true'
        show_sql: 'true'
        type: trace
        hbm2ddl.auto: update
logging:
  level:
    com.zaxxer.hikari: TRACE
    com.zaxxer.hikari.HikariConfig: DEBUG
